#include <meshutil/double_crossing.hpp>

#include <array>
#include <exception>
#include <iostream>

namespace dc = meshutil::double_crossing;

int main() {
    try {
        // Cube corners use i = x + 2*y + 4*z. A thin slab normal to x lies
        // wholly between x=0 and x=1, so all eight corners are outside.
        // Edges 0..3 point in +x, and each meets both sides of the slab.
        const unsigned corner_mask = 0;
        const std::array<unsigned, 12> crossings = {2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0};
        const auto cube = dc::cube_boundary_loops_from_counts(corner_mask, crossings);

        std::cout << "Thin slab: all corners outside, four grid edges crossed twice.\n";
        std::cout << "Symbolic boundary loops: " << cube.loops.size() << '\n';
        for (std::size_t i = 0; i < cube.loops.size(); ++i) {
            std::cout << "  Loop " << i << ':';
            for (unsigned id : cube.loops[i]) {
                const auto node = dc::decode_cube_node(id);
                if (node.kind == dc::CubeNode::Kind::EdgeCrossing) {
                    std::cout << " edge[" << unsigned(node.index)
                              << "].hit[" << unsigned(node.slot) << ']';
                } else {
                    std::cout << " face[" << unsigned(node.index)
                              << "].turn[" << unsigned(node.slot) << ']';
                }
            }
            std::cout << " -> start\n";
        }

        // A separate face example shows why a double crossing that returns
        // through the same edge needs an interior turn, not an edge segment.
        const auto face = dc::lookup_face_from_counts(0, std::array<unsigned, 4>{2, 0, 0, 0});
        std::cout << "\nSame-edge return on one face:\n";
        for (unsigned i = 0; i < face.path_count; ++i) {
            const auto& path = face.paths[i];
            std::cout << "  edge[" << unsigned(path.start / 2)
                      << "].hit[" << unsigned(path.start % 2) << ']';
            if (path.has_yellow) std::cout << " -> face-interior turn";
            std::cout << " -> edge[" << unsigned(path.end / 2)
                      << "].hit[" << unsigned(path.end % 2) << "]\n";
        }
        std::cout << "\nNo mesh is generated by this example. The caller supplies sorted,\n"
                     "deduplicated edge intersections, face-turn geometry shared by adjacent\n"
                     "cells, and geometry-aware loop triangulation with consistent normals.\n"
                     "Counts above two are rejected; they are not silently truncated.\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << error.what() << '\n';
        return 1;
    }
}
